// Dashboard: GET /p/:project — self-contained HTML page
import { FastifyInstance } from 'fastify';

// Build the static HTML as concatenated strings (Perry can't handle large template literals)
const HTML_PART1 = '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Chirp Dashboard</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#0d1117;color:#e6edf3;padding:2rem}.container{max-width:960px;margin:0 auto}h1{font-size:1.8rem;margin-bottom:.5rem}.subtitle{color:#8b949e;margin-bottom:2rem}.stats{display:flex;gap:1.5rem;margin-bottom:2rem;flex-wrap:wrap}.stat-card{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:1.2rem;min-width:160px}.stat-value{font-size:2rem;font-weight:700;color:#58a6ff}.stat-label{color:#8b949e;font-size:.85rem;margin-top:.3rem}.section{margin-bottom:2rem}.section h2{font-size:1.2rem;margin-bottom:1rem;color:#c9d1d9}.chart-container{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:1.5rem}.chart-container svg{width:100%;height:auto}.bar{fill:#58a6ff}.bar:hover{fill:#79c0ff}.breakdown-table{width:100%;border-collapse:collapse;background:#161b22;border:1px solid #30363d;border-radius:8px;overflow:hidden}.breakdown-table th,.breakdown-table td{padding:.7rem 1rem;text-align:left;border-bottom:1px solid #30363d}.breakdown-table th{background:#1c2128;color:#8b949e;font-size:.8rem;text-transform:uppercase}.breakdown-table td{font-size:.9rem}';

const HTML_PART2 = '.period-select{background:#21262d;color:#e6edf3;border:1px solid #30363d;border-radius:6px;padding:.4rem .8rem;font-size:.9rem;cursor:pointer;margin-bottom:1.5rem}.event-tabs{display:flex;gap:.5rem;margin-bottom:1.5rem;flex-wrap:wrap}.event-tab{background:#21262d;border:1px solid #30363d;border-radius:6px;padding:.4rem .8rem;cursor:pointer;font-size:.85rem;color:#c9d1d9}.event-tab.active{background:#58a6ff;color:#0d1117;border-color:#58a6ff}.loading{color:#8b949e;font-style:italic}.error{color:#f85149}</style></head><body><div class="container"><h1 id="title">Chirp</h1><p class="subtitle" id="subtitle">Loading...</p><div><select class="period-select" id="periodSelect"><option value="7d">Last 7 days</option><option value="30d" selected>Last 30 days</option><option value="90d">Last 90 days</option><option value="12m">Last 12 months</option><option value="all">All time</option></select></div><div class="stats" id="stats"></div><div class="event-tabs" id="eventTabs"></div><div class="section"><h2>Event Timeline</h2><div class="chart-container" id="chartContainer"><p class="loading">Loading chart...</p></div></div><div class="section" id="breakdownSection" style="display:none"><h2 id="breakdownTitle">Dimension Breakdown</h2><div id="breakdownContainer"></div></div></div>';

const HTML_PART3 = '<script>var PROJECT=window.location.pathname.split("/").pop();var API=window.location.origin;var projectInfo=null;var currentEvent=null;var currentPeriod="30d";function fetchJSON(u){return fetch(u).then(function(r){if(!r.ok)throw new Error(r.statusText);return r.json()})}function loadProject(){fetchJSON(API+"/api/v1/project/"+PROJECT).then(function(info){projectInfo=info;document.getElementById("title").textContent=info.displayName||info.name;document.getElementById("subtitle").textContent="Total events: "+info.totalCount+(info.firstEvent?" | Since "+info.firstEvent:"");var tabs=document.getElementById("eventTabs");tabs.innerHTML="";info.events.forEach(function(ev,i){var tab=document.createElement("div");tab.className="event-tab"+(i===0?" active":"");tab.textContent=ev.name+" ("+ev.totalCount+")";tab.onclick=function(){selectEvent(ev.name,tab)};tabs.appendChild(tab)});if(info.events.length>0){currentEvent=info.events[0].name;loadEventData()}}).catch(function(e){document.getElementById("subtitle").innerHTML="<span class=error>Failed: "+e.message+"</span>"})}';

const HTML_PART4 = 'function selectEvent(n,el){currentEvent=n;document.querySelectorAll(".event-tab").forEach(function(t){t.classList.remove("active")});el.classList.add("active");loadEventData()}function loadEventData(){if(!currentEvent)return;fetchJSON(API+"/api/v1/query?project="+PROJECT+"&event="+currentEvent+"&period="+currentPeriod).then(function(data){document.getElementById("stats").innerHTML="<div class=stat-card><div class=stat-value>"+data.total+"</div><div class=stat-label>Total Events</div></div><div class=stat-card><div class=stat-value>"+data.uniqueClients+"</div><div class=stat-label>Unique Clients</div></div><div class=stat-card><div class=stat-value>"+(data.series?data.series.length:0)+"</div><div class=stat-label>Active Days</div></div>";renderChart(data.series||[])}).catch(function(e){document.getElementById("chartContainer").innerHTML="<p class=error>Failed: "+e.message+"</p>"});var ev=null;if(projectInfo&&projectInfo.events){for(var i=0;i<projectInfo.events.length;i++){if(projectInfo.events[i].name===currentEvent){ev=projectInfo.events[i];break}}}if(ev&&ev.dimensions&&ev.dimensions.length>0){document.getElementById("breakdownSection").style.display="";loadBreakdowns(ev.dimensions)}else{document.getElementById("breakdownSection").style.display="none"}}';

const HTML_PART5 = 'function renderChart(series){var c=document.getElementById("chartContainer");if(!series.length){c.innerHTML="<p class=loading>No data for this period</p>";return}var mx=0;for(var i=0;i<series.length;i++){if(series[i].count>mx)mx=series[i].count}var w=900,h=300,p=50,g=2;var bw=Math.max(1,(w-p*2)/series.length-g);var bars="";for(var i=0;i<series.length;i++){var x=p+i*(bw+g);var bh=mx>0?(series[i].count/mx)*(h-p*2):0;var y=h-p-bh;bars+="<rect class=bar x="+x+" y="+y+" width="+bw+" height="+bh+"><title>"+series[i].date+": "+series[i].count+"</title></rect>"}var labels="";var step=Math.max(1,Math.floor(series.length/8));for(var i=0;i<series.length;i+=step){var x=p+i*(bw+g)+bw/2;labels+="<text x="+x+" y="+(h-10)+" text-anchor=middle fill=#8b949e font-size=10>"+series[i].date.slice(5)+"</text>"}var yl="";for(var i=0;i<=4;i++){var v=Math.round(mx*(i/4));var y=h-p-((h-p*2)*i/4);yl+="<text x="+(p-5)+" y="+(y+4)+" text-anchor=end fill=#8b949e font-size=10>"+v+"</text>";yl+="<line x1="+p+" y1="+y+" x2="+(w-p)+" y2="+y+" stroke=#30363d stroke-dasharray=2,2/>"}c.innerHTML="<svg viewBox=\\"0 0 "+w+" "+h+"\\">"+yl+bars+labels+"</svg>"}';

const HTML_PART6 = 'function loadBreakdowns(dims){var c=document.getElementById("breakdownContainer");c.innerHTML="";for(var di=0;di<dims.length;di++){(function(dim){fetchJSON(API+"/api/v1/query?project="+PROJECT+"&event="+currentEvent+"&period="+currentPeriod+"&group_by="+dim).then(function(data){if(!data.breakdown||!data.breakdown.length)return;var h="<h3 style=\\"color:#8b949e;margin:1rem 0 .5rem;font-size:.95rem\\">"+dim+"</h3><table class=breakdown-table><thead><tr><th>"+dim+"</th><th>Count</th><th>Unique</th></tr></thead><tbody>";for(var i=0;i<data.breakdown.length;i++){var r=data.breakdown[i];h+="<tr><td>"+(r.value||"—")+"</td><td>"+r.count+"</td><td>"+r.unique+"</td></tr>"}h+="</tbody></table>";var d=document.createElement("div");d.innerHTML=h;c.appendChild(d)}).catch(function(){})})(dims[di])}}document.getElementById("periodSelect").addEventListener("change",function(e){currentPeriod=e.target.value;loadEventData()});loadProject()</script></body></html>';

export async function dashboardRoutes(app: FastifyInstance) {
    app.get<{ Params: { project: string } }>('/:project', async (request, reply) => {
        reply.header('Content-Type', 'text/html');
        return HTML_PART1 + HTML_PART2 + HTML_PART3 + HTML_PART4 + HTML_PART5 + HTML_PART6;
    });
}
